"""Digit-free cover sentences for encode→decode tasks."""

from __future__ import annotations

# Short plain sentences; each is paired with both bits at load time.
BUFFERS: tuple[str, ...] = (
    "The cat sat on the mat.",
    "Rain fell softly on the roof.",
    "She opened the window for fresh air.",
    "The library was quiet after lunch.",
    "Birds gathered near the empty fountain.",
    "He left the note on the kitchen table.",
    "Snow covered the path before dawn.",
    "The river moved slowly past the mill.",
    "A candle flickered in the hallway.",
    "They walked home through the park.",
    "The bread cooled on the wooden board.",
    "Fog hung low over the harbor.",
    "She tied her scarf against the wind.",
    "The dog slept beside the fireplace.",
    "Leaves drifted across the stone steps.",
    "He poured tea into the chipped cup.",
    "The train whistle echoed in the valley.",
    "Moonlight silvered the quiet lake.",
    "Children chased each other across the yard.",
    "The shopkeeper swept the front sidewalk.",
    "A bicycle leaned against the fence.",
    "Steam rose from the morning coffee.",
    "The orchard smelled of ripe apples.",
    "Waves brushed the empty shoreline.",
    "She folded the letter into her pocket.",
    "The attic smelled of dust and pine.",
    "Clouds gathered above the distant hills.",
    "He wound the clock before bed.",
    "The garden gate creaked in the breeze.",
    "A sparrow hopped along the windowsill.",
    "The painter cleaned brushes in the sink.",
    "Warm light spilled from the bakery door.",
    "They shared an umbrella in the drizzle.",
    "The meadow shimmered after the storm.",
    "She hummed while sorting the laundry.",
    "The old map curled at the corners.",
    "Crickets sang beyond the porch light.",
    "He stacked firewood beside the shed.",
    "The violin case rested under the chair.",
    "Twilight settled over the empty street.",
)
